version: 2

project_name: mini-crawler

before:
  hooks:
    - go mod tidy

builds:
  - id: mini-crawler
    main: .
    binary: mini-crawler
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - >-
        -s -w
        -X github.com/kai687/mini-crawler/cmd.version={{ .Version }}
        -X github.com/kai687/mini-crawler/cmd.commit={{ .Commit }}
        -X github.com/kai687/mini-crawler/cmd.date={{ .Date }}

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md
      - LICENSE

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
