[tools]
go = "latest"
gofumpt = "latest"
golangci-lint = "latest"
golangci-lint-langserver = "latest"
golines = "latest"
gum = "latest"
"go:github.com/incu6us/goimports-reviser/v3" = "latest"
"go:golang.org/x/tools/gopls" = "latest"

[tasks.all]
depends = ["build", "format", "lint", "test"]

[tasks.build]
description = "Build the project"
run = "go build"

[tasks.lint]
description = "Lint the code with golangci-lint"
run = "golangci-lint run --fix"

[tasks.format]
description = "Format the code with golangci-lint"
run = "golangci-lint fmt"

[tasks.test]
description = "Run Go tests"
run = "go test ./..."

[tasks.indexing]
description = "Index algolia docs"
depends = "build"
run = '''
gum confirm "Run indexing now?" &&
./docs-crawler -workers 16 https://www.algolia.com/doc/sitemap.xml | algolia objects import docs_clean -F -
'''

[tasks.set-settings]
description = "Configure docs index"
depends = "build"
run = '''
algolia settings set docs_clean \
  --searchableAttributes "unordered(methodName),unordered(hierarchy.lvl0),unordered(hierarchy.lvl1),unordered(hierarchy.lvl2),unordered(hierarchy.lvl3),unordered(hierarchy.lvl4),unordered(hierarchy.lvl5),unordered(hierarchy.lvl6),unordered(content)" \
  --attributesForFaceting "contentType,breadcrumbHierarchy.lvl0,breadcrumbHierarchy.lvl1,breadcrumbHierarchy.lvl2" \
  --customRanking "asc(position)" \
  --ranking "attribute,typo,words,filters,proximity,exact,custom" \
  --indexLanguages en \
  --queryLanguages en \
  --ignorePlurals true \
  --distinct true \
  --attributeForDistinct urlWithoutAnchor
'''
